# Generated by Django 4.2.7 on 2025-10-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
