# Generated by Django 4.2.25 on 2025-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feature_choice',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feature_reason',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes_dislikes_text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='problems_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
